flowchart LR
  Student[Student]
  Admin[Admin]
  FE[Web Frontend]
  Auth[Authentication Module]
  TM[Test Management Module]
  Eval[Evaluation Module]
  Analytics[Analytics Module]
  Queue[(Message Queue)]
  Worker[Code Worker]
  DB[(DB)]

  Student --> FE
  Admin --> FE
  FE --> Auth
  FE --> TM
  FE --> Eval
  FE --> Analytics
  Eval --> Queue
  Queue --> Worker
  Worker --> DB
  TM --> DB
  Auth --> DB
  Analytics --> DB
